services:
  jupyter:
    image: karimelbarbary2024/lab1
    ports:
      - "8888:8888"
    env_file:
      - .env
    volumes:
      - ./:/problem5
    networks:
      - dbnetwork
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgresdata:/var/lib/postgresql/data
    networks:
      - dbnetwork

volumes:
  postgresdata:

networks:
  dbnetwork: